[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mss>=10.0.0",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "requests>=2.32.4",
]
